//TODOS: Add TypeScript

export const loadDataOnCategory = [
     {
          category: 'Artesanais',
          imgURL: "/BurguerWallpaplper.svg",
          products: [
               {
                    id: 1,
                    imgURL: "/MontroSA.jpg",
                    name: 'Monster SA',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend 130g',
                    salad: 'Alface, Tomate',
                    descripition: ' Bacon + Cheddar Artesanal',
                    molhos: 'Barbecue',
                    price: 18.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 2,
                    imgURL: "/PhotoPink.jpg",
                    name: 'Pink Cheese',
                    bread: 'Pão de Batata.',
                    carnes: '1x Carne - Blend 130g',
                    salad: 'Alface, Tomate',
                    descripition: ' Cebola Caramelizada + Queijo Reino ',
                    molhos: 'Barbecue',
                    price: 26.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 3,
                    imgURL: "/Spicy.jpg",
                    name: 'Spicy Burguer',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend 130g',
                    descripition: ' Mel com Pimenta + Queijo Coalho ',
                    price: 18.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 4,
                    imgURL: "/Lion.jpg",
                    name: 'Lion Cheese',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend 130g',
                    descripition: ' Picles + Cebola Roxa Picada + Cheddar Artesanal',
                    price: 18.00,
                    type: 'Artesanal',
                    molhos: 'Ketchup, Mostarda',
                    qtdd: 0,
               },
               {
                    id: 5,
                    imgURL: "/Tauros.jpg",
                    name: 'Tauros Burguer',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend 130g',
                    salad: 'Alface',
                    descripition: 'Cebola Caramelizada + Cheddar Artesanal',
                    price: 18.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 6,
                    imgURL: "/Duplo.jpg",
                    name: 'Duplo Monster',
                    bread: 'Pão de Batata',
                    carnes: '2x Carne - Blend 130g(Cada)',
                    descripition: 'Bacon + Cebola Caramelizada + Cheddar Artesanal',
                    price: 29.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 7,
                    imgURL: "/Feroz.jpg",
                    name: 'Feroz Burguer',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend 130g',
                    salad: 'Alface, Tomate',
                    descripition: 'Cebola Caramelizada + Queijo Coalho',
                    price: 19.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 8,
                    imgURL: "/Feroz.jpg",
                    name: 'Pig Monster',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend de porco 130g',
                    salad: 'Alface, Tomate',
                    descripition: 'Cebola Caramelizada + Queijo Coalho',
                    price: 20.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 29,
                    imgURL: "/5Star.jpg",
                    name: '5 Estrela',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend 130g',
                    descripition: 'Cebola na manteiga + Queijo Mussarela + Carne do Sol',
                    price: 23.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 30,
                    imgURL: "/PegaTombo.jpg",
                    name: 'Pega no Tombo',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend 130g',
                    descripition: 'Queijo Coalho + Carne do Sol Desfiada + Melaço',
                    price: 24.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 31,
                    imgURL: "/Triplo.jpg",
                    name: 'Triplo Monster',
                    bread: 'Pão de Batata',
                    carnes: '3x Carne - Blend 130g(Cada)',
                    descripition: 'Cheddar Artesanal',
                    price: 34.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 32,
                    imgURL: "/Chicken.jpg",
                    name: 'Monster Chicken',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend de frango 130g',
                    descripition: 'Queijo Mussarela + Bacon + Cebola Roxa',
                    salad: 'Alface, Tomate',
                    molhos: ' Molho Big Mac',
                    price: 20.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 59,
                    imgURL: "/BurguerCheese.jpg",
                    name: 'Burguer Cheese',
                    bread: 'Pão de Batata',
                    carnes: '1x Carne - Blend 130g',
                    descripition: 'Cheddar Artesanal',
                    price: 15.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
          
          ]
     },
     {
          category: 'Hot Dog',
          imgURL: "/HotDogWalpalper.svg",
          products: [
               {
                    id: 9,
                    imgURL: "/DogSimples.jpg",
                    name: 'Dog Simples',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: ' Queijo Ralado + Batata Palha ',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 8.00,
                    qtdd: 0,
               },
               {
                    id: 10,
                    imgURL: "/DogPaulista.jpg",
                    name: 'Dog Paulista',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Batata Palha + Puré',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 9.00,
                    qtdd: 0,
               },
               {
                    id: 11,
                    imgURL: "/DogBacon.jpg",
                    name: 'Dog Bacon',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Bacon + Puré + Batata Palha + Queijo Ralado',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 10.00,
                    qtdd: 0,
               },
               {
                    id: 12,
                    imgURL: "/DogFrango.jpg",
                    name: 'Dog Frango',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Frango + Puré + Batata Palha + Queijo Ralado',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 11.00,
                    qtdd: 0,
               },
               {
                    id: 13,
                    imgURL: "/DogItalia.jpg",
                    name: 'Dog Italia',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Carne moída + Frango + Puré + Batata Palha + Queijo Ralado',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 11.00,
                    type: 'Artesanal',
                    qtdd: 0,
               },
               {
                    id: 14,
                    imgURL: "/DogPrensado.jpg",
                    name: 'Dog Prensado',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Queijo Mussarela + Batata Palha',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 8.00,
                    qtdd: 0,
               },
               {
                    id: 15,
                    imgURL: "/DogCaipira.jpg",
                    name: 'Dog Caipira',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Frango + Cheddar + Batata Palha',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 13.00,
                    qtdd: 0,
               },
               {
                    id: 16,
                    imgURL: "/DogAmerica.jpg",
                    name: 'Dog America',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Calabresa + Queijo Mussarela + Frango + Catupiry + Batata Palha',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 15.00,
                    qtdd: 0,
               },
               {
                    id: 17,
                    imgURL: "/BigHotDog.jpg",
                    name: 'Big Hot Dog',
                    bread: 'Pão de Hot Dog',
                    carnes: '2x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Bacon + Cheddar + Catupiry + Batata Palha',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 17.00,
                    qtdd: 0,
               },
               {
                    id: 33,
                    imgURL: "/MDog.jpg",
                    name: 'Monster Dog',
                    bread: 'Pão de Hot Dog',
                    carnes: '1x Salsicha',
                    salad: 'Tomate, Milho, Ervilha',
                    descripition: 'Bacon  + Batata Palha + Purê + Carne + Frango + Queijo Mussarela',
                    molhos: 'Barbecue, Ketchup, Maionese',
                    price: 20.00,
                    qtdd: 0,
               },
          ]
     },
     {
          category: 'Tradicionais',
          imgURL: "/BurguerWallpalper.svg",
          products: [
               {
                    id: 18,
                    imgURL: "/XBacon.jpg",
                    name: 'X-Bacon',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: ' Bacon, queijo ',
                    molhos: 'Barbecue',
                    price: 11.00,
                    qtdd: 0,

               },
               {
                    id: 19,
                    imgURL: "/XCalabresa.jpg",
                    name: 'X-Calabresa',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: ' Calabresa, queijo ',
                    molhos: 'Barbecue',
                    price: 11.00,
                    qtdd: 0,
               },
               {
                    id: 20,
                    imgURL: "/XFrango.jpg",
                    name: 'X-Frango',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: ' Frango, queijo. ',
                    molhos: 'Barbecue',
                    price: 10.00,
                    qtdd: 0,
               },
               {
                    id: 21,
                    imgURL: "/XBauru.jpg",
                    name: 'X-Bauru',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: 'Presunto + Queijo. ',
                    molhos: 'Barbecue',
                    price: 9.50,
                    qtdd: 0,
               },
               {
                    id: 22,
                    imgURL: "/XBurguer.jpg",
                    name: 'X-Burguer',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: 'Queijo. ',
                    molhos: 'Barbecue',
                    price: 9.00,
                    qtdd: 0,
               },
               {
                    id: 23,
                    imgURL: "/XEgg.jpg",
                    name: 'X-Egg',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: 'Ovo + Presunto + Queijo. ',
                    molhos: 'Barbecue',
                    price: 11.00,
                    qtdd: 0,
               },
               {
                    id: 24,
                    imgURL: "/Monstrao.jpg",
                    name: 'Monstrão',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: 'Ovo + Bacon  + Frango + Calabresa + Presunto + Queijo',
                    molhos: 'Barbecue',
                    price: 19.00,
                    qtdd: 0,
               }, 
               {
                    id: 25,
                    imgURL: "/Misto.jpg",
                    name: 'Misto Quente',
                    bread: 'Pão de hamburguer.',
                    descripition: 'Queijo + Presunto',
                    price: 5.00,
                    qtdd: 0,
               },
               {
                    id: 26,
                    imgURL: "/XSalada.jpg",
                    name: 'X-Salada',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: 'Presunto + Queijo',
                    molhos: 'Barbecue',
                    price: 10.00,
                    qtdd: 0,
               },
               {
                    id: 27,
                    imgURL: "/BBurguer.jpg",
                    name: 'Big Burguer',
                    bread: 'Pão de hamburguer.',
                    carnes: '2x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: '2 Ovos + Presunto + 2 Queijos',
                    molhos: 'Barbecue',
                    price: 17.00,
                    qtdd: 0,
               },
               {
                    id: 28,
                    imgURL: "/BDog.jpg",
                    name: 'Burguer Dog',
                    bread: 'Pão de hamburguer.',
                    carnes: '1x Carne - De hamburguer',
                    salad: 'Alface, Tomate, Milho, Ervilha.',
                    descripition: 'Batata palha + Salsicha + Calabresa + Bacon + Queijo',
                    molhos: 'Barbecue',
                    price: 17.00,
                    qtdd: 0,
               },
          ]
     },
     {
          category: 'Batata Frita',
          imgURL: "/PotatoWallpalper.svg",
          products: [
               {
                    id: 34,
                    imgURL: "/BTT.jpg",
                    name: 'Batata Tradicional',
                    // size: '350g',
                    peso: 'M',
                    descripition: 'Com Sal',
                    price: 16.00,
                    qtdd: 0,
               },
               {
                    id: 35,
                    imgURL: "/BR.jpg",
                    name: 'Batata Recheada',
                    // size: '350g',
                    peso: 'M',
                    descripition: 'Cheddar + Bacon ou Cheddar + Catupiry + Frango ou Catupiry + Carne do sol',
                    price: 20.00,
                    qtdd: 0,
                    warning: 'Ao fechar o carrinho, insira em observações seu tipo de Batata',
               },
               {
                    id: 36,
                    imgURL: "/BTCS.jpg",
                    name: 'Batata Especial',
                    // size: '350g',
                    peso: 'M',
                    descripition: 'Catupiry +  Carne do Sol + Mussarela + Queijo do reino + Queijo Coalho + Carne Moída + Bacon',
                    price: 45.00,
                    qtdd: 0,
                    warning: 'Ao fechar o carrinho, insira em observações seu tipo de Batata',

               },
          ]
     },
     {
          category: 'Bebida',
          imgURL: "/Photo-Burguer.png",
          products: [
               {
                    id: 42,
                    imgURL: "/EnergeticoMonster.jpg",
                    name: 'Energético Monster',
                    size: '437ml',
                    price: 12.00
               },
               {
                    id: 44,
                    imgURL: "/ChaMatte.jpg",
                    name: 'Chá Matte Limão',
                    size: '250ml',
                    price: 3.00
               },
               {
                    id: 45,
                    imgURL: "/ChaMatte2.jpg",
                    name: 'Chá Matte Pessego',
                    size: '250ml',
                    price: 3.00
               },
               {
                    id: 46,
                    imgURL: "/H2O.jpg",
                    name: 'H2O',
                    size: '500ml',
                    price: 6.00
               },
               {
                    id: 47,
                    imgURL: "/AguaSgás.jpg",
                    name: 'Água sem gás',
                    size: '500ml',
                    price: 3.00
               },
               {
                    id: 48,
                    imgURL: "/AguaCgás.jpg",
                    name: 'Água com gás',
                    size: '500ml',
                    price: 3.00
               },
               {
                    id: 49,
                    imgURL: "/JuniSukitLaranja.jpg",
                    name: 'Juninho S. Laranja',
                    size: '200ml',
                    price: 3.00
               },
               {
                    id: 55,
                    imgURL: "/JuninhoAntartica.jpg",
                    name: 'Juninho Antartica',
                    size: '200ml',
                    price: 3.00
               },
               {
                    id: 50,
                    imgURL: "/LataSodaLimonada.jpg",
                    name: 'Lata Soda Limonada',
                    size: '350ml',
                    price: 5.00
               },
               {
                    id: 51,
                    imgURL: "/JuniSodaLimao.jpg",
                    name: 'Juninho Soda Limão',
                    size: '200ml',
                    price: 3.00
               },
               {
                    id: 52,
                    imgURL: "/Juninho Pepsi.jpg",
                    name: 'Juninho Pepsi',
                    size: '350ml',
                    price: 3.00
               },
               {
                    id: 53,
                    imgURL: "/LataPepsi.jpg",
                    name: 'Lata Pepsi',
                    size: '350ml',
                    price: 5.00
               },
               {
                    id: 57,
                    imgURL: "/LataCoca.jpg",
                    name: 'Lata Coca',
                    size: '350ml',
                    price: 5.00
               },
               {
                    id: 56,
                    imgURL: "/LitroAntartica.jpg",
                    name: 'Litro Antartica',
                    size: '1 Litro',
                    price: 8.00
               },
               {
                    id: 54,
                    imgURL: "/LitroPepsi.jpg",
                    name: 'Litro Pepsi',
                    size: '1 Litro',
                    price: 8.00
               },
               {
                    id: 58,
                    imgURL: "/LitroCoca.jpg",
                    name: 'Litro Coca',
                    size: '1 Litro',
                    price: 8.00
               },
          ]
     },
     {
          category: 'Milk Shake',
          imgURL: "/MilkShakeWallpaplper.svg",
          products: [
               {
                    id: 37,
                    imgURL: "/MilkShaOreo.jpg",
                    name: 'Milk Shake Oreo',
                    size: '500ml',
                    price: 12.00
               },
               {
                    id: 38,
                    imgURL: "/MilkShaChocol.jpg",
                    name: 'Milk Shake Chocolate',
                    size: '500ml',
                    price: 12.00
               },
               {
                    id: 39,
                    imgURL: "/MilkShaMoran.jpg",
                    name: 'Milk Shake Morango',
                    size: '500ml',
                    price: 12.00
               },
               {
                    id: 40,
                    imgURL: "/MilkShaOvoMal.jpg",
                    name: 'Milk Shake Ovomaltine',
                    size: '500ml',
                    price: 12.00
               },
               {
                    id: 41,
                    imgURL: "/MilkShaPaçoca.jpg",
                    name: 'Milk Shake Paçoca',
                    size: '500ml',
                    price: 12.00
               },
          ]
     },
]


