import StyledConfig from '@/styles/_styled.config'
import GlobalStyle from '@/styles/_globalStyled'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { relative } from 'path'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Monster Gourmet Express',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{position: 'relative'}}>
        <GlobalStyle />
        <StyledConfig>{children}</StyledConfig>
      </body>
    </html>
  )
}
